---
title: "Introduction of 2022 CAB members"
description: |
  This article introduces you to what the members of the CAB are.
author:
  - name: Bioconductor Community Advisory Board
    url: https://bioconductor.org/about/community-advisory-board/
date: 2022-05-12
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The Bioconductor [Community Advisory Board](https://bioconductor.org/about/community-advisory-board/)
adds new members every year.

In this article, we will first introduce the newly joined members as well as the existing members.

## 

### Xueyi Dong (From 2022)


### Leo Lahti (From 2022)

Leo Lahti (PhD 2010; machine learning & bioinformatics) has contributed to R & Bioconductor since early 2000's. He is now leading a research team at the Department of Computing, University of Turku, Finland and actively engaged in national and international networks in open data science. The team has developed statistical software in particular for microbiome studies and computational humanities, and provides regular training on these topics. Lahti is committed to strengthening the R/Bioconductor networks especially in the Northern Europe.

<datascience.utu.fi> | [@antagomir](//twitter.com/antagomir)


### Nicole Ortogero (From 2022)


### Janani Ravi (From 2022)
Janani Ravi is currently an Assistant Professor at the Departments of Pathobiology and Diagnostic Investigation, Microbiology and Molecular Genetics, Michigan State University. She completed her PhD in Computational Biology at Virginia Tech and her postdoctoral research at the Public Health Research Institute, Rutgers Biomedical and Health Sciences. Her research group at MSU works on developing computational approaches to study the molecular basis of pathogenesis and intervention of infectious diseases, using protein sequence-structure-function relationships, comparative genomics, and drug repurposing.

Janani is also actively engaged in training, education, and outreach. She is committed to creating and sustaining a diverse and inclusive ecosystem in data science and R for learners and professionals alike, focusing on increasing the participation of underrepresented minorities in data science and R programming. Towards this effort, she founded R-Ladies East Lansing and co-founded Women+ Data Science and AsiaR.

<jravilab.github.io> | [@janani137](//twitter.com/janani137)

### Hedia Tnani (From 2022)


### Daniela Cassol (From 2021)


### Estefania Mancini (From 2021)


### Kevin Rue-Albrecht (From 2021)


### Mike Smith (From 2021)


### Yagoub A. I. Adam (From 2020)


### Benilton Carvalho (From 2020)


### Leonardo Collado-Torres (From 2020)


### Aedin Culhane (From 2020)


### Susan Holmes (From 2020)


### Kozo Nishida (From 2020)

Kozo is an research software engineer in Japan.
He works on the CAB "event calendar" and "multilingual" working group.
He hosted BioC Asia 2021 as an organizing comittee.
He is engaged in overcoming language barriers and trying to spread Bioconductor
to non-English speaking people.

### Johannes Rainer (From 2020)


### Matt Ritchie (From 2020)


### Lori Shepherd (From 2020)



## Past members

### Saskia Freytag (2020 ~ 2022)


### Katerina Kechris (2021 ~ 2022)

