# Local-only preview workflow for forks. Do not commit to upstream repo.

name: Preview Fork Branch

on:
  push:
    branches-ignore:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
  
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
